#!/usr/bin/env python

import hashlib
import sys
import pyperclip

if len(sys.argv) < 2:
    print("No string to hash")

result = hashlib.md5(sys.argv[1].encode())

md5 = result.hexdigest()
print(md5)
pyperclip.copy(md5)
